### ISSUE TITLE
Smite (and likely others) becomes permanent if revived in MvM

### ISSUE THREAD

**Issue by slipsy** [Phil25/RTD#73] opened 2023-12-02 21:33 UTC
Playing a server running MvM and RTD, friend rolled smite and died, I revived them and the effect became permanent on them, causing them to repeatedly take damage/die without constant healing. This persisted through further reviving, respawning naturally, and even reconnecting or map changing. Rerolling does remove the effect.

**Comment by Phil25** [comment] 2023-12-10 19:02
Are there any error logs from before you disconnected?

**Comment by naydef** [comment] 2023-12-10 19:06
No errors from before I disconnect. Errors appear only after disconnecting.

**Comment by Phil25** [comment] 2023-12-17 20:28
@slipsy Did this happen multiple times for you? I cannot reproduce it, dying in MvM simply removes the perk due to a regular death event for me before the revive happens. Also, were you able to access server logs by any chance?

@naydef I cannot reproduce this either, it looks like both situations include some edge case which doesn't happen in normal circumstances. But I have to ask, am I correct to assume you compiled the plugin yourself? Were there any significant changes introduced?

I had my theories as to why you experiences these issues, and they should be fixed with 0a52864aa6f125839de8ba29a4282019b7c3aaee and ffdd70f6e1f647c251cd9f7aaa97f533f0cce358. However, since I'm not able to reproduce the issues I cannot really prove it.

In any case, ffdd70f6e1f647c251cd9f7aaa97f533f0cce358 introduced a few fail safes to how perk times are run. If a random error occurs somewhere, it should be less detrimental now (especially in relation to @naydef's error log). It will still be an error which needs to be fixed though.

**Comment by Phil25** [comment] 2023-12-17 20:29
In any case, I'm gonna go ahead with the 2.4.1 release which fixes another bug I was able to reproduce. Again, I cannot confirmed whether this issue specifically is fixed, but please do update and look out of any errors if you can.

**Comment by naydef** [comment] 2023-12-17 20:37
@Phil25 Yea, compiled it myself. Only significant change was removing the updater code.

**Comment by Phil25** [comment] 2023-12-17 20:42
Still prepping to release it :)

Also, updater code doesn't do anything if you don't have the updater plugin or `sm_rtd2_autoupdate` is disabled. Even so, updater include file is an optional compilation dependency, so if it won't be found the updater code will be removed automatically.

**Comment by naydef** [comment] 2023-12-17 20:48
However there are some variables that do nothing if updater include is not there, which generates warnings. And we are compiling with `-E` option, which fails our plugin autotesting.

**Comment by Phil25** [comment] 2023-12-17 20:57
> some variables that do nothing if updater include is not there, which generates warnings

I see, this should be now fixed in 2086b748eea041e513d8c2f08f6cd01f62f6ce91.

**Comment by Phil25** [comment] 2023-12-17 21:14
This shows that there is a condition which doesn't trigger the perk to be removed when it should. Can you explain what exactly happens so the player gets killed?

**Comment by naydef** [comment] 2023-12-17 21:55
I died to the effect and other ways (smited to death, sm_slay @me, killed by player), no change.

**Comment by Phil25** [comment] 2023-12-17 22:11
Awesome! Yeah this makes sense.

@slipsy could you check if the server you were on happens to have an outdated config as well?

**Comment by Phil25** [comment] 2023-12-18 10:51
As discussed on Discord, further feedback is required to determine if it's an issue with server configuration. I'll close this for now and go ahead with the release. Feel free to reopen.

**Closed by Phil25** 2023-12-18 10:51 UTC
Labels: bug, feedback needed
