### ISSUE TITLE
"Powerplay" 99% resistance to everything is kept if you switch classes while at spawn right after rolling it

### ISSUE THREAD

**Issue by Th3F4ult** [Phil25/RTD#83] opened 2023-12-15 18:11 UTC
It persists through deaths, team changes and going into spectator mode.

I have no logs since I was just playing in a server with RTD 2.4.0.

**Comment by Phil25** [comment] 2023-12-15 18:29
Thanks for repro steps. This is most likely the same issue as #79 but I’ll keep it open just in case it’s something per perk.

I’ll start investigation tomorrow (back from vacation) and roll out a fix asap.

**Comment by Phil25** [comment] 2023-12-17 12:25
I've confirmed this is the same issue. I'm closing it as a duplicate of #79 to direct the discussion there.

**Closed by Phil25** 2023-12-17 12:25 UTC
Labels: bug
