### ISSUE TITLE
Plugin does not load on servers with max player settings over 64 players

### ISSUE THREAD

**Issue by rx149** [Phil25/RTD#104] opened 2024-02-23 17:37 UTC
# Bug description

When setting unrestricted_maxplayers and then setting maxplayers to any number over 64 the rtd plugin refuses to load. I tested both old and the most current version of RTD.

Server log throws these errors:
```
[2024-02-23 12:31:03]: L 02/23/2024 - 17:31:03: [SM] Exception reported: Array index out-of-bounds (index 66, limit 66)`

[2024-02-23 12:31:03]: L 02/23/2024 - 17:31:03: [SM] Blaming: rtd.smx

[2024-02-23 12:31:03]: L 02/23/2024 - 17:31:03: [SM] Call stack trace:

[2024-02-23 12:31:03]: L 02/23/2024 - 17:31:03: [SM] [1] Line 203, u:\Work\Code\RTD\scripting\rtd.sp::InitClientCache

[2024-02-23 12:31:03]: L 02/23/2024 - 17:31:03: [SM] [2] Line 144, u:\Work\Code\RTD\scripting\rtd.sp::OnPluginStart

[2024-02-23 12:31:03]: L 02/23/2024 - 17:31:03: [SM] Unable to load plugin "rtd.smx": Error detected in plugin startup (see error logs)

```
# Report checks

> ### Please describe the bug in the section above, then post it and tick the correct boxes below.

### Required
- [X] The bug does not have an open issue.
- [X] I have described the bug.
- [X] I mentioned whether the bug is sporadic or systematic.

### Optional
- [X] Steps to reproduce the bug are known and have been described.
- [X] I have access to server error logs and have provided them, if any.
- [X] I am able to check the RTD version (`sm_cvar sm_rtd2_version`) and have specified it.
- [ ] I have access to RTD default configuration file (`rtd2_perks.default.cfg`) and can confirm it's the one bundled with plugin release archive.
- [ ] I have access to RTD custom configuration file (`rtd2_perks.custom.cfg` or other) and have attached it to this issue.
- [ ] The issue is related to a particular perk, which has been specified by a label.

**Comment by Phil25** [comment] 2024-02-23 19:26
Hi, this is a known issue. I decided not to support 64+ player servers until SourceMod 1.12 release, which has the necessary changes to make plugins work with unrestricted maxplayers.

I’m closing this as a duplicate of #60, and have also renamed that issue to be easier findable for this reason.

That said, I’ve no problem providing you a custom build which works for unrestricted maxplayers, but I don’t have time right this moment to build anything.

We can continue in #60.

**Closed by Phil25** 2024-02-23 19:26 UTC
Labels: bug
