### ISSUE TITLE
Translations still not working

### ISSUE THREAD

**Issue by GreatBlank** [Phil25/RTD#64] opened 2023-11-22 12:38 UTC
The plugin only uses EN-US language even if you change in-game language.

**Comment by MAGNAT2645** [comment] 2023-11-22 14:27
That's because RTD uses `LANG_SERVER` for phrases as target to retrieve language.
Also some strings still aren't translated at all, just hardcoded.

**Comment by MAGNAT2645** [comment] 2023-11-22 19:30
Functions like `RTDPrint`, `RTDPrintAll`, `RTDPrintAllExcept` should include `SetGlobalTransTarget` so all `%T` can be changed to `%t`.
```sourcepawn
void RTDPrintAll(const char[] sFormat, any ...)
{
	char sMsg[255];
	for (int i = 1; i <= MaxClients; ++i)
	{
		if (!IsClientInGame(i) || IsFakeClient(i))
		{
			continue;
		}
		SetGlobalTransTarget(i);
		VFormat(sMsg, 255, sFormat, 2);
		PrintToChat(i, CHAT_PREFIX ... " %s", sMsg );
	}
}
```

**Comment by Phil25** [comment] 2023-11-22 22:31
Hey, sorry I didn't take a look at it for 2.4.0. This kinda relates to #44 so lemme just reference it here.

The reason it's `LANG_SERVER` is because I saw this being the convention way back in the day when implementing it. I'm gonna have to research the topic of SM translations and see how they're handled basically from scratch, which is one of the reasons I didn't bother with it yet. That alone is not gonna take a long time but I wanna some time for a break because the last update took a lot of time and effort. But suffice to say, this topic is on my radar.

> Also some strings still aren't translated at all, just hardcoded.

@MAGNAT2645 can you let me know which ones? All the player facing strings should be translated afaik.

**Comment by MAGNAT2645** [comment] 2023-11-23 00:06
I can do PR but not right now and idk how much changes need to be done.

**Comment by Phil25** [comment] 2023-12-27 03:17
Closing this as duplicate of #44, I'll be mentioning that issue with the fix.

**Closed by Phil25** 2023-12-27 03:17 UTC
Labels: duplicate, request :: general
